### ISSUE TITLE
Missing \\

### ISSUE THREAD

**Issue by xansiaux** [josephcslater/array_to_latex#10]
Hello,
Thank's a lot for your work.

When I try this code:
```python3
 import numpy as np
import array_to_latex as a2l

A = np.array([[1.23456, 23.45678],[456.23, 8.239521]])
a2l.to_ltx(A, frmt = '{:6.2f}', arraytype = 'pmatrix')
```
I obtain this 👍 
![image](https://user-images.githubusercontent.com/16732402/95381365-58316880-08e8-11eb-9e4b-7c999a338dc2.png)

The last backslashes are missing, and the latex code is wrong.

I use Python 3.8.6

Can you help me?

Best regards,

**Comment by josephcslater** [comment]
I've never typed them in. Does it not compile ok?

**Comment by xansiaux** [comment]
Thanks a lot for your answer.

And excuse me: I was thinking that the code doesn't compile  without backslashes, but it does.

I compile with miktex2.9: 
```
\begin{pycode}
import numpy as np
import array_to_latex as a2l

A = np.array([[1.23456, 23.45678],[456.23, 8.239521]])
print(str(a2l.to_ltx(A, frmt = '{:6.2f}', arraytype = 'pmatrix')))
\end{pycode}
```
and I obtain this:
![image](https://user-images.githubusercontent.com/16732402/95578699-98056680-0a34-11eb-8a59-1dd2e518ba0e.png)

I don't understand why.
Sorry.

**Comment by josephcslater** [comment]
I don't either, but you're running python inside LaTeX so it could be on the LaTeX side. In python, it works fine.

The str command is likely unnecessary. In fact, the print command isn't necessary either. It results in the extra "None" you see. 

<img width="756" alt="image" src="https://user-images.githubusercontent.com/12815335/95579789-da5e8180-09fb-11eb-807b-dc99760fe8cb.png">

**Comment by xansiaux** [comment]
Thank's a lot!
That was the problem.
Without 'print' , it works.
Have a good day!
