### ISSUE TITLE
Unexpected behavior when latex is returned to variable

### ISSUE THREAD

**Issue by benmaier** [josephcslater/array_to_latex#11]
Writing latex code into a variable doesn't work as specified in the readme because the keyword argument is `print_out=True` per default

## behavior

```python
In [118]: import numpy as np
     ...: import array_to_latex as a2l
     ...: A = np.array([[1.23456, 23.45678],[456.23, 8.239521]])
     ...: latex_code = a2l.to_ltx(A, frmt = '{:6.2f}', arraytype = 'array')
     ...:
\begin{array}
    1.23 &   23.46\\
  456.23 &    8.24
\end{array}

In [119]: latex_code is None
Out[119]: True
```
## expected behavior

```python
In [118]: import numpy as np
     ...: import array_to_latex as a2l
     ...: A = np.array([[1.23456, 23.45678],[456.23, 8.239521]])
     ...: latex_code = a2l.to_ltx(A, frmt = '{:6.2f}', arraytype = 'array')
     ...:

In [119]: latex_code 
Out[119]: r"\begin{array}
    1.23 &   23.46\\
  456.23 &    8.24
\end{array}"
```

**Comment by josephcslater** [comment]
I've changed the readme. Please confirm that this works as documented and I'll close this issue. 

Thank you for your report.

**Comment by benmaier** [comment]
Yes, works as documented. May I remark that a function printing a result per default instead of returning the result is somewhat curious, especially since printing the output is only one print statement away. The coding principle behind this being that `print(f())` is way more verbose than `f()` (as someone reading the code has no way of knowing that `f` prints something per default).

**Comment by josephcslater** [comment]
I actually agree. The problem is that it was an early design decision that I've been wary of changing for fear of breaking other code. The first release only printed to the screen as it modelled some other code in a different language. Sending it to a variable happened much later. Ironically, my job means I maintain it to some degree, but almost never use it at all.  

Putting out a release with a warning and an expiration date for the behavior hasn't appealed to me. 

I'm happy to do so if you can help (substantially do). I have very limited time for coding these days.

**Comment by benmaier** [comment]
Right, I completely understand. I recently went ahead and forked your package to rewrite some of your code into functions that worked how I needed them to work personally. It's available under [benmaier/numpyarray_to_latex](https://github.com/benmaier/numpyarray_to_latex). The decision to publish this as a new package rather than opening pull requests for your package was that I had specific needs for typesetting numpy arrays that I didn't want to implement for dataframes as well (marking matrix elements with colors, introducing separators, output to Jupyter notebooks), and that I didn't feel comfortable with to just overwrite your design decisions. I hope that's okay for you (note that I documented you as the original creator of the codebase everywhere).

As a side note, if you wanted to introduce changes that would break backwards compatibility, you could release them as a `(i+1).0.0` version as per [semantic versioning](https://semver.org/spec/v2.0.0.html). Then people would know not to expect their old code to work when upgrading.

**Comment by josephcslater** [comment]
That's exciting! I look forward to seeing where you go with the project. Going in the direction of a new package is the right move. My ability to maintain this one is minimal. I am sure there are better decisions to be made going forward, and I certainly wouldn't have time to adjudicate them fairly. I'm simply amazed that this little snippet of code that is the package has gained such interest. 

I appreciate the recognition. Thanks for the tip on semantic versioning. If I ever get back into coding I'll have to remember that.
