### ISSUE TITLE
Unhelpful exception when give wrong data type to to_ltx

### ISSUE THREAD

**Issue by bfield1** [josephcslater/array_to_latex#7]
In to_ltx, 'a' is required to be a numpy array or pandas dataframe. If 'a' is not an instance of either of those classes, then the function raises an UnboundLocalError, because it passes over the if statements where a variable would be assigned.

It would be more helpful if this situation could be detected (such as by using if-else statements) and a TypeError raised with a meaningful error message.

**Comment by josephcslater** [comment]
Good point. Do you have a suggested patch? It will be a while before I can get to this.

**Comment by bfield1** [comment]
I've opened a pull request with my suggested patch.
